(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
"use strict";function injectStylesheet(s,t){var e=s.createElement("link");e.rel="stylesheet",e.type="text/css",e.href=t,s.head.appendChild(e)}function injectScript(s,t){var e=s.createElement("script");e.type="text/javascript",e.src=t,e.async=!1,s.head.appendChild(e)}function injectAssets(s,t,e){e.forEach(function(e){var n=t.assetRoot+"build/"+t.manifest[e];n.match(/\.css/)?injectStylesheet(s,n):injectScript(s,n)})}function bootHypothesisClient(s,t){if(!s.querySelector('link[type="application/annotator+html"]')){var e=s.createElement("link");e.rel="sidebar",e.href=t.sidebarAppUrl,e.type="application/annotator+html",s.head.appendChild(e);var n=s.createElement("link");n.rel="hypothesis-client",n.href=t.assetRoot+"build/boot.js",n.type="application/annotator+javascript",s.head.appendChild(n),injectAssets(s,t,["scripts/polyfills.bundle.js","scripts/jquery.bundle.js","scripts/annotator.bundle.js","styles/icomoon.css","styles/annotator.css","styles/pdfjs-overrides.css"])}}function bootSidebarApp(s,t){injectAssets(s,t,["scripts/raven.bundle.js","scripts/angular.bundle.js","scripts/katex.bundle.js","scripts/showdown.bundle.js","scripts/polyfills.bundle.js","scripts/unorm.bundle.js","scripts/sidebar.bundle.js","styles/angular-csp.css","styles/angular-toastr.css","styles/icomoon.css","styles/katex.min.css","styles/sidebar.css"])}function boot(s,t){s.querySelector("hypothesis-app")?bootSidebarApp(s,t):bootHypothesisClient(s,t)}module.exports=boot;

},{}],2:[function(require,module,exports){
"use strict";var boot=require("./boot"),settings=require("../shared/settings").jsonConfigsFrom(document);boot(document,{assetRoot:settings.assetRoot||"https://commentingres.mdpi.com/hypothesis/1.81.0/",manifest:{"fonts/KaTeX_AMS-Regular.woff":"fonts/KaTeX_AMS-Regular.woff?d1708b","fonts/KaTeX_Caligraphic-Bold.woff":"fonts/KaTeX_Caligraphic-Bold.woff?bce727","fonts/KaTeX_Caligraphic-Regular.woff":"fonts/KaTeX_Caligraphic-Regular.woff?ff0a2a","fonts/KaTeX_Fraktur-Bold.woff":"fonts/KaTeX_Fraktur-Bold.woff?4fe167","fonts/KaTeX_Fraktur-Regular.woff":"fonts/KaTeX_Fraktur-Regular.woff?22ac05","fonts/KaTeX_Main-Bold.woff":"fonts/KaTeX_Main-Bold.woff?355529","fonts/KaTeX_Main-Italic.woff":"fonts/KaTeX_Main-Italic.woff?0bf8cb","fonts/KaTeX_Main-Regular.woff":"fonts/KaTeX_Main-Regular.woff?76c0fe","fonts/KaTeX_Math-BoldItalic.woff":"fonts/KaTeX_Math-BoldItalic.woff?9a79de","fonts/KaTeX_Math-Italic.woff":"fonts/KaTeX_Math-Italic.woff?a0c5a3","fonts/KaTeX_Math-Regular.woff":"fonts/KaTeX_Math-Regular.woff?741de0","fonts/KaTeX_SansSerif-Bold.woff":"fonts/KaTeX_SansSerif-Bold.woff?0b932c","fonts/KaTeX_SansSerif-Italic.woff":"fonts/KaTeX_SansSerif-Italic.woff?c0cfcc","fonts/KaTeX_SansSerif-Regular.woff":"fonts/KaTeX_SansSerif-Regular.woff?0d52ce","fonts/KaTeX_Script-Regular.woff":"fonts/KaTeX_Script-Regular.woff?30b05b","fonts/KaTeX_Size1-Regular.woff":"fonts/KaTeX_Size1-Regular.woff?ac63f8","fonts/KaTeX_Size2-Regular.woff":"fonts/KaTeX_Size2-Regular.woff?80afd2","fonts/KaTeX_Size3-Regular.woff":"fonts/KaTeX_Size3-Regular.woff?579c05","fonts/KaTeX_Size4-Regular.woff":"fonts/KaTeX_Size4-Regular.woff?44c744","fonts/KaTeX_Typewriter-Regular.woff":"fonts/KaTeX_Typewriter-Regular.woff?6641c6","fonts/h.woff":"fonts/h.woff?0c3a71","styles/angular-csp.css":"styles/angular-csp.css?e61a94","styles/angular-toastr.css":"styles/angular-toastr.css?b84bea","styles/annotator.css":"styles/annotator.css?5be08c","styles/icomoon.css":"styles/icomoon.css?4d21dd","styles/katex.min.css":"styles/katex.min.css?43cde2","styles/pdfjs-overrides.css":"styles/pdfjs-overrides.css?d2387e","styles/sidebar.css":"styles/sidebar.css?c450ab","scripts/angular.bundle.js":"scripts/angular.bundle.js?99b06b","scripts/annotator.bundle.js":"scripts/annotator.bundle.js?f4eed8","scripts/boot.bundle.js":"scripts/boot.bundle.js?d9ccdb","scripts/jquery.bundle.js":"scripts/jquery.bundle.js?88ca68","scripts/katex.bundle.js":"scripts/katex.bundle.js?442a9c","scripts/polyfills.bundle.js":"scripts/polyfills.bundle.js?a00597","scripts/raven.bundle.js":"scripts/raven.bundle.js?5f8990","scripts/showdown.bundle.js":"scripts/showdown.bundle.js?89332a","scripts/sidebar.bundle.js":"scripts/sidebar.bundle.js?651b59","scripts/unorm.bundle.js":"scripts/unorm.bundle.js?7d3812"},sidebarAppUrl:settings.sidebarAppUrl||"https://commenting.mdpi.com/app.html"});

},{"../shared/settings":3,"./boot":1}],3:[function(require,module,exports){
"use strict";function assign(n,o){for(var t in o)o.hasOwnProperty(t)&&(n[t]=o[t]);return n}function jsonConfigsFrom(n){for(var o={},t=n.querySelectorAll("script.js-hypothesis-config"),e=0;e<t.length;e++){var s;try{s=JSON.parse(t[e].textContent)}catch(n){console.warn("Could not parse settings from js-hypothesis-config tags",n),s={}}assign(o,s)}return o.theme="clean",o.enableExperimentalNewNoteButton=!0,o}module.exports={jsonConfigsFrom:jsonConfigsFrom};

},{}]},{},[2])
